### ISSUE TITLE
Hello, can you provide client and run tutorial

### ISSUE THREAD

**Issue by Liuccysdgg** [ZettaStudios/crossfire#5]
I like your project very much. I have v1122 client, but I can't run with your server source code. We look forward to your tutorial

**Comment by 0rangeFox** [comment]
Hey, this is still a project under development and not yet ready for the production, please follow up more on the [C# project](https://github.com/ZettaStudios/crossfire-dotnet), because that is what is being developed right now, and then it will be ported to this language with better code and structuring.

**Comment by guinhx** [comment]
Currently the server is working with the CF Phoenix client
